version: '3.3'
services:
  process_data:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: process_data
    volumes:
      - .:/app
    working_dir: /app

volumes:
  app:
